[package]
name = "nittei_utils"
description = "Nittei utils"
license = "MIT"
version = "0.1.0"
authors = ["Fredrik Meringdal"]
edition = "2021"

[lints]
workspace = true

[dependencies]
rand = "0.8.0"
config = "0.14"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.5.0"
